const MPI_MAC_FIELD_ORDER = [
  "MPI_TRANS_TYPE",
  "MPI_MERC_ID",
  "MPI_PAN",
  "MPI_CARD_HOLDER_NAME",
  "MPI_PAN_EXP",
  "MPI_CVV2",
  "MPI_TRXN_ID",
  "MPI_ORI_TRXN_ID",
  "MPI_PURCH_DATE",
  "MPI_PURCH_CURR",
  "MPI_PURCH_AMT",
  "MPI_ADDR_MATCH",
  "MPI_BILL_ADDR_CITY",
  "MPI_BILL_ADDR_STATE",
  "MPI_BILL_ADDR_CNTRY",
  "MPI_BILL_ADDR_POSTCODE",
  "MPI_BILL_ADDR_LINE1",
  "MPI_BILL_ADDR_LINE2",
  "MPI_BILL_ADDR_LINE3",
  "MPI_SHIP_ADDR_CITY",
  "MPI_SHIP_ADDR_STATE",
  "MPI_SHIP_ADDR_CNTRY",
  "MPI_SHIP_ADDR_POSTCODE",
  "MPI_SHIP_ADDR_LINE1",
  "MPI_SHIP_ADDR_LINE2",
  "MPI_SHIP_ADDR_LINE3",
  "MPI_EMAIL",
  "MPI_HOME_PHONE",
  "MPI_HOME_PHONE_CC",
  "MPI_WORK_PHONE",
  "MPI_WORK_PHONE_CC",
  "MPI_MOBILE_PHONE",
  "MPI_MOBILE_PHONE_CC",
  "MPI_LINE_ITEM",
  "MPI_RESPONSE_TYPE"
];

const CALLBACK_MAC_FIELD_ORDER = [
  "MPI_MERC_ID",
  "MPI_TRXN_ID",
  "MPI_ERROR_CODE",
  "MPI_APPR_CODE",
  "MPI_RRN",
  "MPI_BIN",
  "MPI_REFERRAL_CODE",
  "MPI_CARDHOLDER_INFO"
];

module.exports = {
  MPI_MAC_FIELD_ORDER,
  CALLBACK_MAC_FIELD_ORDER
};
